name: Build-Deploy-Prod
on:
  push:
    branches: [feature/vaccount_auth_provider]

env: 
  APP_NAME: bitorbit-synapse
  REPO: ${{ secrets.GAR_PROD }}/${{ secrets.GCP_PROD_PROJECT }}/docker
  IMAGE_TAG: ${{ github.sha }}
  BRANCH_NAME: ${{ github.ref_name }}
  ENVIRONMENT: prod-london

jobs:
  docker-build:
    name: Build and push
    runs-on: prod-london
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/setup-gcloud@v0
      - name: Build, tag, and push image 
        env:
          DOCKER_BUILDKIT: 1
        run: |
          gcloud auth configure-docker ${{ secrets.GAR_PROD }} -q
          docker build -t $REPO/$APP_NAME:$IMAGE_TAG . -f docker/Dockerfile
          docker tag $REPO/$APP_NAME:$IMAGE_TAG $REPO/$APP_NAME:${BRANCH_NAME//\//_}
          docker push $REPO/$APP_NAME:$IMAGE_TAG
          docker push $REPO/$APP_NAME:${BRANCH_NAME//\//_}
  deploy:
    name: Deploy via Helmfile
    runs-on: prod-london
    needs: docker-build
    steps:
      - name: Check out bitorbit-prod-infra
        uses: actions/checkout@v3
        with:
          repository: BitorbitLabs/bitorbit-prod-infra
          ref: master
          ssh-key: ${{ secrets.SSH_KEY_PROD_INFRA }}
      - uses: google-github-actions/setup-gcloud@v0
      - name: Authenticate to GAR Helm registry
        run: gcloud auth configure-docker ${{ secrets.GAR_PROD }} -q
      - name: Deploy via helmfile
        id: deploy
        env:
          UPDATE_REPOS: "true"
        run: >
          cd helmfile &&
          helmfile -e ${ENVIRONMENT} -l name=${APP_NAME}
          apply --skip-needs
          --set image.tag=${IMAGE_TAG}
          --set image.repository=${REPO}/${APP_NAME}