name: Deploy to dev
on:
  push:
    branches: [develop,ci_devnet]

jobs:
  docker-build:
    # Name the Job
    name: Build and push
    runs-on: build
    outputs:
      repository: ${{ steps.build.outputs.repository }}
      image_tag: ${{ steps.build.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
          registry: ${{ secrets.REGISTRY_HOST }}
      - name: Build, tag, and push image to AWS ECR
        id: build
        env:
          REGISTRY: ${{ secrets.REGISTRY_HOST}}/velas
          REPOSITORY: velas-synapse
          IMAGE_TAG: ${{github.sha}}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG --no-cache -f docker/Dockerfile .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
  deploy:
    name: Deploy via Helmfile
    runs-on: deployer
    needs: docker-build
    container:
      image: quay.io/roboll/helmfile:v0.142.0
    steps:
      - name: Install ssh
        run: apk --update add openssh-client
      - name: Check out velas-infra
        uses: actions/checkout@master
        with:
          repository: velas/velas-infra
          ref: master
          ssh-key: ${{ secrets.SSH_KEY_INFRA }}
      - uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA_EU_MONSTER1_RAW }}
          context: "prod-eu-monster1"
      - name: Sops Binary Installer
        uses: mdgreenwald/mozilla-sops-action@v1.1.0
      - uses: adnsio/setup-age-action@v1.2.0
      - name: Deploy via helmfile
        id: deploy
        env:
          REGISTRY: ${{ secrets.REGISTRY_HOST }}/velas
          REPOSITORY: velas-synapse
          IMAGE_TAG: ${{github.sha}}
          SOPS_AGE_KEY: ${{ secrets.INFRA_AGE }}
        run: |
          helm plugin install https://github.com/jkroepke/helm-secrets --version v3.11.0 || true
          helm plugin install https://github.com/databus23/helm-diff || true
          cd deploy/prod-eu-monster1
          helmfile -l namespace=devnet,name=velas-synapse apply  --set image.tag=$IMAGE_TAG,image.repository=$REGISTRY/$REPOSITORY --skip-deps
